"""compras y costo unitario en venta

Revision ID: 9db9974986cc
Revises: aa98ab774886
Create Date: 2026-08-21 00:15:54.379956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9db9974986cc'
down_revision: Union[str, None] = 'aa98ab774886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venta_detalle', sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True))
    # Backfill de ventas hechas antes de que existiera esta columna: se usa el costo
    # actual del producto como mejor aproximacion disponible (no se registro en su momento).
    op.execute(
        """
        UPDATE venta_detalle vd
        SET costo_unitario = p.costo
        FROM productos p
        WHERE vd.producto_id = p.id AND vd.costo_unitario IS NULL
        """
    )
    op.alter_column('venta_detalle', 'costo_unitario', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta_detalle', 'costo_unitario')
    op.drop_table('compras')
    # ### end Alembic commands ###
